
module.exports = {
    username: 'huudanhnguyen',
    password: '2366huudanh',
    database: 'training_nodejs',
    col_items: 'items',
    col_products: 'products',
    col_sliders: 'sliders',
    col_users: 'users',
    col_categories: 'categories',
    col_articles: 'articles',
    col_menu: 'menu',
    col_rss: 'rss',
    col_settings: 'settings',
    col_attributes: 'attributes',
    col_blogArticle: "blogArticle",
    col_blogCategory: "blogCategory",
    col_contact: 'contact',
    col_newsletter: 'newsletter',
    col_discount: 'discount',
    col_coupons: 'coupons',
};