
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    ERROR_NAME: 'Chiều dài Name từ %d đến %d ký tự',
    ERROR_NAME_EMPTY: 'Name không được để trống',
    ERROR_TITLE_EMPTY: 'Tiêu đề không được để trống',
    ERROR_NAME_EMPTY: 'Tên sản phẩm không được để trống',
    ERROR_ORDERING: 'Ordering phải là số',
    ERROR_PRICE: 'Giá tiền phải là số nguyên',
    ERROR_STATUS: 'Status phải là một giá trị khác rỗng',
    ERROR_COLOR: 'Màu sắc phải là một giá trị khác rỗng',
    ERROR_SIZE: 'Kích cỡ phải là một giá trị khác rỗng',
    ERROR_Category: 'Vui lòng chọn Category',
    ERROR_SLUG: 'Slug không hợp lệ',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ',
    ERROR_FILE_EMPTY: 'Vui lòng chọn file hình',
    ERROR_LOGIN_USERNAME_NOTEXIST: 'Username không tồn tại',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Password không chính xác',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',


    ADD_SUCCESS: 'Add Successfully',
    EDIT_SUCCESS: 'Edit Successfully',
    ERROR_NAME: 'Name length must be from %d to %d',
    ERROR_NAME_EMPTY: 'Name must be non-empty',
    ERROR_NAME_DUPLICATED: 'Duplicated Name',
    ERROR_TITLE: 'Title length must be from %d to %d',
    ERROR_TITLE_EMPTY: 'Title must be non-empty',
    ERROR_TITLE_DUPLICATED: 'Duplicated Title',
    ERROR_ORDERING: 'Ordering must be number from %d to %d',
    ERROR_QUANTITY: 'Quantity must be number from %d',
    ERROR_STATUS: 'Status must be choose',
    ERROR_CATEGORY: "Category must be choose",
    ERROR_CATEGORY_INVALID: "Category is invalid",
    ERROR_SLUG: 'Invalid Slug',
    ERROR_SLUG_DUPLICATED: 'Duplicated Slug',
    ERROR_FILE_LIMIT: 'Invalid Size File',
    ERROR_FILE_EXTENSION: 'Invalid Type File',
    ERROR_FILE_EMPTY: 'Must upload photo',
    ERROR_DESCRIPTION: 'Description must be non-empty',
    ERROR_DETAIL: 'Detail must be non-empty',
    ERROR_SOURCE: 'Source must be non-empty',
    ERROR_SETTING_TITLEPAGE: 'Please input Title Page',
    ERROR_SETTING_ADDRESS: 'Please input Address',
    ERROR_SETTING_PHONENUMBER: 'Please input Phone Number',
    ERROR_SETTING_EMAIL: 'Please input valid Email',
    ERROR_SETTING_COPPYRIGHT: 'Please input Coppyright',
    ERROR_SETTING_URLFACEBOOK: 'Input link Facebook wrong',
    ERROR_SETTING_URLTWITTER:'Input link Twitter wrong',
    RROR_SETTING_URLINSTAGRAM:'Input link Instagram wrong',
    ERROR_SETTING_URLYOUTUBE:'Input link Youtube wrong',
    ERROR_SETTING_URLLINKEDIN:'Input link LinkedIN wrong',
    ERROR_SLIDER_URL:'Input link invalid',
    ERROR_RSS_URL:"Input link wrong",
    ERROR_SUBJECT: 'Subject must be non-empty',
    ERROR_API_EMPTY: 'API must be non-empty',
    ERROR_EMAIL: "Please input valid Email",
    ERROR_MESSAGE: "Please input Message",
    SUCCESS_SETTING_SAVE: 'Save Setting Successfully',
    ERROR_NOT_EXITS: 'Not Exits',
    ERROR_DISCOUNT_UNIT: 'Discount Value is Percent or Money',
    ERROR_COUPON_UNIT: 'Coupon Value is Percent or Money',
    ERROR_DISCOUNT_MONEY: 'Money must be number from %d',
    ERROR_MINTOTAL_MONEY: 'Money MINTOTAL must be number from %d',
    ERROR_MAXDOWN_MONEY: 'Money Max Down must be number from %d',
    ERROR_DISCOUNT_PERCENT: 'Percent must be number from > %d to < %d',
    ERROR_DISCOUNT_LISTPRODUCT: 'List product must be non-empty',
    ERROR_DISCOUNT_LISTPRODUCT_INVALID:'List product invalid',
    ERROR_SLIDER_TEXTBUTTON: 'Text button length must be from %d to %d',
    ERROR_SLIDER_HEADERTITLE: 'Hearder title must be from %d to %d',
    ERROR_SLIDER_TITLE: 'Title must be from %d to %d',
    ERROR_SLIDER_DESCRIPTION: 'Desciption must be from %d to %d',
    ERROR_SETTING_SUBJECT_EMAIL: 'Subject Email length must be from %d',
    ERROR_SETTING_CONTENT_EMAIL: 'Content Email length must be from %d',
    ERROR_SETTING_TITLE_CLIENT: 'Title What Client Say must be non-empty',
    ERROR_SETTING_LIST_CLIENT: 'List Client Say must be non-empty',
    ERROR_SETTING_LIST_CLIENT_VALUE: 'List Client Say is invalid',
    ERROR_SETTING_LIST_MISSION: 'List Mission must be non-empty',
    ERROR_SETTING_LIST_MISSION_VALUE: 'List Mission is invalid',
    ERROR_SETTING_TITLE_ABOUTUS: 'Title of About US page must be non-empty',
    ERROR_SETTING_CONTENT_ABOUTUS: 'Content of About US page must be non-empty',
    ERROR_SETTING_DATA_ABOUTUS: 'Data of About US page must be number',
    ERROR_EMAIL_DUPLICATED: 'Duplicated Email',
    ERROR_SETTING_TITLE_CHOOSE: 'Title of CHOOSE US page must be non-empty',
    ERROR_SETTING_DESCRIPTION_CHOOSE: 'DESCRIPTION of CHOOSE US page must be non-empty',
    ERROR_SETTING_LINK_CHOOSE: 'LINK of CHOOSE US page must be non-empty',
    ERROR_COST:'Cost must be non-empty',
    ERROR_COST_SHIP:'Cost must be from %d VND',
    ERROR_REGISTER_EMAIL: 'Vui lòng nhập đúng Email.',
    ERROR_REGISTER_NAME: 'Vui lòng nhập Tên của bạn (Độ dài từ %d đến %d )',
    ERROR_REGISTER_PASS_INPUT: ' Vui lòng nhập đầy đủ Mật Khẩu và Nhập lại Mật Khẩu',
    ERROR_REGISTER_PASS: 'Vui lòng nhập Mật Khẩu của bạn (Độ dài từ %d đến %d )',
    ERROR_REGISTER_PASSCONFIRM: 'Mật Khẩu và nhập lại của bạn phải trùng nhau',
    ERROR_REGISTER_POLICY: 'Vui lòng tick để đồng ý quy định của chúng tôi',
    ERROR_REGISTER_CHECKUSER: 'Email này đã đăng ký tài khoản.',
    ERROR_LOGIN_CHECKUSER: 'Email này chưa đăng ký tài khoản',
    ERROR_LOGIN_PASS: "Mật khẩu không chính xác",
};